### ISSUE TITLE
[BUG] Manga Manager unresponsive when choosing files to edit

### ISSUE THREAD

**Issue by Drazzilb08** [MangaManagerORG/Manga-Manager#138]
**Describe the bug**

**To Reproduce**
Using latest docker pull on unraid OS

When importing a folder you see all items being imported, after that the program thinks multiple files are selected. 
Conversation held on discord: [Here](https://discord.com/channels/821879810934439936/932272866970451998/1072591654806098002)

**Expected behavior**
When selecting individual issues I expect poster art to change as well as summary information

**Screenshots**
See discord

**Desktop (please complete the following information):**
 - OS: unraid OS running docker, latest pull
 - Browser Safari
 - Version beta 0.0.0

**Comment by ThePromidius** [comment]
Managed to reproduce on both latest and develop. Its completely unresponsive. Looking into this
