### ISSUE TITLE
Cover Downloader failing to load

### ISSUE THREAD

**Issue by Dgenner** [MangaManagerORG/Manga-Manager#175]
Version: v1.0.2.1 (current stable as of posting)
Python Version: 3.10.11

![MMerror](https://user-images.githubusercontent.com/35158055/232170852-7e551ae5-eaaf-4a2f-bdc2-dc56ab524961.png)

**Comment by majora2007** [comment]
This isn't helpful without more information

**Comment by ThePromidius** [comment]
Cover downloader is not implemented yet that's why its failing.
