### ISSUE TITLE
Webp converter no longer checks for filesize after conversion

### ISSUE THREAD

**Issue by Roshri** [MangaManagerORG/Manga-Manager#176]
Sometimes when converting files from .png to .webp, the result is a bigger filesize than the original. This defeats the purpose of the conversion an sometimes the result is a bigger .cbz 
This was issue #106  and was solved some time ago

Since the rework I've seen a lot of files suffer from this again so I was wondering if the check could be brought back in.

**Comment by ThePromidius** [comment]
Handled in #178
