### ISSUE TITLE
Settings not saving

### ISSUE THREAD

**Issue by DieselTech** [MangaManagerORG/Manga-Manager#180]
**Describe the bug**
On windows 10, the programs settings don't seem to be saving. Going to `C:\Users\%USERNAME%\MangaManager` does not show any config files. Just a logs directory. 

**To Reproduce**
1. Open App
2. Configure settings from within MM
3. Click `Save` within MM
4. Restart App
5. Check settings in MM and see nothing has saved

**Expected behavior**
Settings are supposed to save in the users profile.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10, 22H2
 - Version: 1.0.2.1

**Comment by ThePromidius** [comment]
Can't replicate

**Comment by DieselTech** [comment]
I think I figured it out. There was confusion for me because checking the box for "test_welcome_to_mm" is checked when it's disabled. I was loading the app, seeing it was checked and unchecking it. Then on next load it would show the welcome messages again. Without extra text there describing it I didn't realize that checked = off. 

I see the settings.ini in the same folder as the mediamanager exe file, but the wording of the dialogs inside MM settings is also confusing. Clicking "Open settings folder" takes you to the user profile, but no settings are being saved there since it's dropped next to the exe.
