### ISSUE TITLE
Open Folder not working after a batch process

### ISSUE THREAD

**Issue by Roshri** [MangaManagerORG/Manga-Manager#183]
**Describe the bug**
Sometimes after processing a bunch of files, when I click on "Open Folder", the program freezes.
A workaround is selecting any existing file, clicking on "Filename Fill" and then the buttons work again.

**To Reproduce**
1. Select a folder with some .cbz files (containing .webp images) with the "Open Folder" button
2. Modify the data as wanted
3. Process
4. Click "Open Folder" again
5. The program freezes and some  buttons are greyed out, aditionally it stops showing the modified data

**Expected behavior**
"Open folder" should open a new dialog to select the folder

**Screenshots**
![image](https://github.com/MangaManagerORG/Manga-Manager/assets/29184137/6e179b11-28d8-4d0d-9386-7626127b92af)

**Desktop (please complete the following information):**
 - OS: w10

EDIT: After using the program for a while, I noticed this bug happens mostly after I edit cover images along metadata.
Notice I have set a default directory for covers, which is located on my desktop.

**Comment by DieselTech** [comment]
Having the same issue, it will process the files in the folder once after doing the cover manager. Then trying to click on 'Open Folder' again causes the error.

![image](https://github.com/MangaManagerORG/Manga-Manager/assets/30128380/b7f67130-48b2-414a-b891-b4737b656b2b)

**Comment by ThePromidius** [comment]
Didn't manage to reproduce. 
However, I did handle the error posted by DieselTech not sure how it will handle it nor if it will fix the root problem
