### ISSUE TITLE
Failed to import extension on windows

### ISSUE THREAD

**Issue by DieselTech** [MangaManagerORG/Manga-Manager#186]
**Describe the bug**
Just opening MM on windows without doing anything else there is a stack trace for missing plugin

**To Reproduce**
1. Open App
2. Check error log

**Expected behavior**
No errors on start. 

**Screenshots**
![image](https://github.com/MangaManagerORG/Manga-Manager/assets/30128380/d00b3b25-1bbb-4ad3-a205-c6703ff65ec1)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10

**Additional context**

**Comment by majora2007** [comment]
What version of the software in the About dialog?

**Comment by ThePromidius** [comment]
This is known. Cover downloader is not a functioning feature yet.
Silencing the error can be done for now
