### ISSUE TITLE
[Feature Request] Cover Manager: Select all "Front" and "Back" covers. 

### ISSUE THREAD

**Issue by DieselTech** [MangaManagerORG/Manga-Manager#192]
**Is your feature request related to a problem? Please describe.**
There isn't an easy way to select bulk covers to remove. It's a lot of clicking and scrolling when there is tag images at the front and back of every single file. 

**Describe the solution you'd like**
A button for selecting all the front and back covers in cover manager to save my poor mouse from having to click 100+ times just to select everything.

**Comment by ThePromidius** [comment]
iirc you can shift click and it will select all the images in between

**Comment by DieselTech** [comment]
> iirc you can shift click and it will select all the images in between

Just tested this on v1.0.4 and it doesn't work.
