### ISSUE TITLE
[Feature Request] Add bookmark to a page like ComicTagger

### ISSUE THREAD

**Issue by k3ltfalcon** [MangaManagerORG/Manga-Manager#215]
**Is your feature request related to a problem? Please describe.**
When I convert manga to an EPUB or MOBI version, I want it to include a table of contents, so I can easily navigate to the chapter I want to read.

**Describe the solution you'd like**
I want it to have a feature that allows me to bookmark a page with the chapter name.

**Describe alternatives you've considered**
I used ComicTagger before. It has that feature, but the software only allows saving per volume. I want to batch all the volumes and save them at once.
**Additional context**
This is a picture of ComicTagger with that feature.
![image](https://github.com/user-attachments/assets/62463b85-8c8d-4dc0-8325-37bd0eb02f3b)

**Comment by majora2007** [comment]
I'm not understanding, Manga Manager doesn't support converting to Epub nor does the ComicInfo spec support any concept of a table of contents. Can you clarify what you're asking for?

**Comment by k3ltfalcon** [comment]
I use Komga to manage my manga, but I usually read on my Kindle. So, I use Kindle Comic Converter to convert them to EPUB. If ComicInfo includes bookmarks, the EPUB will have a table of contents after conversion. I typically use ComicTagger for this, but the software doesn’t allow batch editing.

**Comment by k3ltfalcon** [comment]
> I'm not understanding, Manga Manager doesn't support converting to Epub nor does the ComicInfo spec support any concept of a table of contents. Can you clarify what you're asking for?

I use Komga to manage my manga, but I usually read on my Kindle. So, I use Kindle Comic Converter to convert them to EPUB. If ComicInfo includes bookmarks, the EPUB will have a table of contents after conversion. I typically use ComicTagger for this, but the software doesn’t allow batch editing.

**Comment by majora2007** [comment]
ComicInfo as a spec doesn't support Bookmarks or a Table of contents. Epub files do. Manga Manager doesn't work with epubs.

**Comment by k3ltfalcon** [comment]
> ComicInfo as a spec doesn't support Bookmarks or a Table of contents. Epub files do. Manga Manager doesn't work with epubs.

Thank you for your information
