### ISSUE TITLE
CLI support + volume specific meta data (comicvine) + mangadex Cover support (hitting kavita api to upload the covers)

### ISSUE THREAD

**Issue by edgehub-cloud** [MangaManagerORG/Manga-Manager#78]
for bulk processing with a simple find command with ./*cb/ , to add/update meta data , for volumes fetching meta data from comicvine, comictagger written in python should be easy to merge for that solutioon , while adding meta data per chapter from different sources like mangadex , since mangadex only has volume related covers only . one solution would be to host own database with mixture of anilist ,mangadex, and comicvine (even for covers)

**Comment by ThePromidius** [comment]
This was partially introduced in #98 and #102 so i'm closing this
