### ISSUE TITLE
[Outdated] Volume Manager naming incorrect

### ISSUE THREAD

**Issue by HerrFrutti** [MangaManagerORG/Manga-Manager#96]
**Describe the bug**
Naming not corret, BLEACH -> BLEA Vol. XX CH XXX.cbz
Think the "CH" is interpreted as chapter...
**Expected behavior**
BLEACH -> BLEACH Vol. XX [...].cbz
**Screenshots**
![image](https://user-images.githubusercontent.com/6975702/193459232-bfc771a4-68f4-4904-a74a-46425d6d1338.png)

**Desktop (please complete the following information):**
 - OS: WIN10
 - Browser Brave
 - Version v1.44.105

**Comment by ThePromidius** [comment]
Nice find! This actually happens because i parse "Ch" as chapter to place the Vol.xx just before

**Comment by ThePromidius** [comment]
Closing this issue as MM has been reworked and the codebase does no longer apply.
Will have this into account once volume manager is implemented in the rework,
